### Student Marks Array

In [1]:
import numpy as np

marks = np.array([78, 65, 89, 56, 92])

print("Marks:", marks)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Dimension:", marks.ndim)
print("Data type:", marks.dtype)

Marks: [78 65 89 56 92]
Shape: (5,)
Size: 5
Dimension: 1
Data type: int64


### Student Marks Access

In [2]:
import numpy as np

marks = np.array([72, 85, 64, 90, 76])

print("Marks:", marks)

# Indexing
print("First student:", marks[0])
print("Third student:", marks[2])
print("Last student:", marks[-1])

# Slicing
print("First three students:", marks[:3])
print("Students 2 to 4:", marks[1:4])
print("Last two students:", marks[-2:])

Marks: [72 85 64 90 76]
First student: 72
Third student: 64
Last student: 76
First three students: [72 85 64]
Students 2 to 4: [85 64 90]
Last two students: [90 76]


### Subject-wise Marks

In [3]:
import numpy as np

marks = np.array([
    78, 85, 90,
    65, 72, 80,
    88, 91, 84,
    56, 62, 70,
    95, 89, 92
])

marks = marks.reshape(5, 3)

print("Student-wise marks:")
print(marks)

print("Shape:", marks.shape)

Student-wise marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Shape: (5, 3)


### Internal and External Marks

In [4]:
import numpy as np

internal = np.array([18, 16, 19, 15, 17])
external = np.array([70, 65, 72, 60, 75])

final_marks = internal + external

print("Internal marks:", internal)
print("External marks:", external)
print("Final marks:", final_marks)

Internal marks: [18 16 19 15 17]
External marks: [70 65 72 60 75]
Final marks: [88 81 91 75 92]


### Pass Percentage Analysis

In [5]:
import numpy as np

marks = np.array([45, 78, 56, 32, 91])

passed = marks[marks >= 50]

print("Marks:", marks)
print("Students scoring 50 or above:", passed)

Marks: [45 78 56 32 91]
Students scoring 50 or above: [78 56 91]


### Average Marks

In [6]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

average = np.mean(marks, axis=1)

print("Marks:")
print(marks)

print("Average marks of each student:")
print(average)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Average marks of each student:
[84.33333333 72.33333333 87.66666667 62.66666667 92.        ]


### Class Performance Statistics

In [7]:
import numpy as np

marks = np.array([67, 82, 91, 74, 58])

print("Marks:", marks)

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Marks: [67 82 91 74 58]
Total: 372
Average: 74.4
Highest: 91
Lowest: 58
Standard deviation: 11.46472851837321


### Subject-wise Performance

In [8]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

subject_total = np.sum(marks, axis=0)

print("Marks:")
print(marks)

print("Total marks in each subject:")
print(subject_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks in each subject:
[382 399 416]


### Student-wise Performance

In [9]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])

student_total = np.sum(marks, axis=1)

print("Marks:")
print(marks)

print("Total marks of each student:")
print(student_total)

Marks:
[[78 85 90]
 [65 72 80]
 [88 91 84]
 [56 62 70]
 [95 89 92]]
Total marks of each student:
[253 217 263 188 276]


### Student Ranking

In [11]:
import numpy as np

marks = np.array([245, 278, 219, 290, 256])
sorted_marks = np.sort(marks)[::-1]
print("Original marks:", marks)
print("Marks in descending order:", sorted_marks)
ranking = np.argsort(marks)[::-1]

print("Student ranking:")
for rank, student_index in enumerate(ranking, start=1):
    print("Rank", rank, "- Student", student_index + 1,
          "- Marks:", marks[student_index])
    

Original marks: [245 278 219 290 256]
Marks in descending order: [290 278 256 245 219]
Student ranking:
Rank 1 - Student 4 - Marks: 290
Rank 2 - Student 2 - Marks: 278
Rank 3 - Student 5 - Marks: 256
Rank 4 - Student 1 - Marks: 245
Rank 5 - Student 3 - Marks: 219


### Duplicate Marks Analysis

In [12]:
import numpy as np

marks = np.array([85, 92, 85, 76, 92])

unique_marks = np.unique(marks)

print("Original marks:", marks)
print("Unique marks:", unique_marks)

Original marks: [85 92 85 76 92]
Unique marks: [76 85 92]


### Missing Marks

In [13]:
import numpy as np

marks = np.array([78, 85, np.nan, 92, 67])

average = np.nanmean(marks)

print("Marks:", marks)
print("Average excluding missing value:", average)

Marks: [78. 85. nan 92. 67.]
Average excluding missing value: 80.5


### Grade Classification

In [14]:
import numpy as np

marks = np.array([95, 82, 74, 61, 45])

grades = np.select(
    [
        marks >= 90,
        marks >= 80,
        marks >= 70,
        marks >= 60
    ],
    [
        "A",
        "B",
        "C",
        "D"
    ],
    default="F"
)

print("Marks:", marks)
print("Grades:", grades)

Marks: [95 82 74 61 45]
Grades: ['A' 'B' 'C' 'D' 'F']


### Random Marks Generation

In [16]:
import numpy as np
marks = np.random.randint(0, 101, 5)

print("Randomly generated marks:", marks)

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Standard deviation:", np.std(marks))

Randomly generated marks: [48 86  0 11 76]
Total: 221
Average: 44.2
Highest: 86
Lowest: 0
Standard deviation: 34.14322773259728
